name: Alexa Proxy
version: 1.0.0
slug: alexa_proxy
description: Alexa Proxy for Home Assistant
url: https://github.com/w35l3y/hassio-addons/tree/main/alexa_proxy
ingress: false
init: false
apparmor: true
panel_icon: mdi:docker
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map: []
startup: services
boot: auto
environment:
  NODE_ENV: production
  PORT: "3000"
ports:
  3000/tcp: "3015"
options:
  env_vars:
    - name: OPTS_HA_BASE_URL
      value: http://homeassistant:8123
    - name: OPTS_HA_TOKEN
      value: ""
schema:
  env_vars:
    - name: match(^OPTS_HA_([A-Z0-9_])+$)
      value: str

